server:
  port: 9000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: forumdb
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG